DROP TABLE IF EXISTS EXAM;

CREATE TABLE EXAM (
	ID INT NOT NULL AUTO_INCREMENT,
	CODE INT NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	UNIQUE UQ_EXAM_CODE (CODE),
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS STUDENT_EXAM;

CREATE TABLE STUDENT_EXAM (
	 ID INT NOT NULL AUTO_INCREMENT
	, STUDENT_ID INT NOT NULL
	, EXAM_ID INT NOT NULL
	, PASSED BIT DEFAULT 0
	, MARK INT NOT NULL DEFAULT 0
	,PRIMARY KEY(ID)
	, CONSTRAINT FK_STUDENT_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAM (ID)
);